modality: ???

seed: 34

model:
  model_name: ???
  residual_block: bottleneck
  T: 16
  num_classes: 400
  pretrained: false

optimization:
  lr: 0.1
  wd: 4.0e-5
  warmup: 0
  epochs: 75
  train_bs: ???
  val_bs: ???
  accumulate_batches: 1

training:
  num_nodes: ???
  continue_training: ???
  job_id: ???
  train_num_workers: 14
  val_num_workers: 7

scale_invariant_setup:
  train_on_sphere: false
  scale_invariant: false
  elr: 1.0e-4
  linear_norm: 10

data_preprocessing:
  crop_size: 224
  min_resize_size: 256
  max_resize_size: 320
  snippets_per_val_sample: 10